@startuml
title Tensor Analysis
start
split
:Spread Mapping;
split again
#HotPink:Linear Space;
end split
:Linear Space with Tension Mapping
<math>Aox ... oxA = Pm</math>
It's called an m-order tensor space;

:Elements in an m-order tensor space are called m-order tensors;

split
 :Tensor addition
 A，BPm，A + - B = ;
 split again
 :Tensor subtraction;
 split again
  :Number of tensor;
 end split

:Tensor function;
:Tensor Analysis;
stop
@enduml